services:
  - type: web
    name: dukalangu-pro
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        value: localhost
  - type: database
    name: localhost
    databaseName: dukalangu_db
    user: root
    plan: free